// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9jK3IJ3dwbZXiffzJVoPiBv4OHdR3AmI',
    appId: '1:14326744664:web:f053377704ed821a8bac2d',
    messagingSenderId: '14326744664',
    projectId: 'chat-app-26d08',
    authDomain: 'chat-app-26d08.firebaseapp.com',
    databaseURL: 'https://chat-app-26d08-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-26d08.appspot.com',
    measurementId: 'G-7FDP34KYX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABzxsvmuELRgasJCdyCtfEbD2t7jwNGlo',
    appId: '1:14326744664:android:7f332fbc2777a1f38bac2d',
    messagingSenderId: '14326744664',
    projectId: 'chat-app-26d08',
    databaseURL: 'https://chat-app-26d08-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-26d08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL5aF30e8l6tUFYlkYTQH-jdh8JerzAV8',
    appId: '1:14326744664:ios:f477528483b1ef618bac2d',
    messagingSenderId: '14326744664',
    projectId: 'chat-app-26d08',
    databaseURL: 'https://chat-app-26d08-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-26d08.appspot.com',
    iosClientId: '14326744664-18tu6lrbegpce3jqtkd8uqu06upflcnj.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL5aF30e8l6tUFYlkYTQH-jdh8JerzAV8',
    appId: '1:14326744664:ios:b11c8b7a526918578bac2d',
    messagingSenderId: '14326744664',
    projectId: 'chat-app-26d08',
    databaseURL: 'https://chat-app-26d08-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-26d08.appspot.com',
    iosClientId: '14326744664-shv710qnqse7ffub17cdqbmn15dsfii9.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholar.RunnerTests',
  );
}
